name: Deploy Landing Page to GitHub Pages

on:
  repository_dispatch:
    types: [deploy-landing-page]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Landing Page Directories
        run: |
          mkdir -p docs/dashboard
          mkdir -p docs/${{ github.event.client_payload.slug }}

      - name: Download Static HTML Files
        run: |
          # Download homepage static HTML
          curl -k -v -L "${{ secrets.RAPSITE_APP_URL }}/api/export-homepage" -o "docs/index.html"
          
          # Download static dashboard wrapper HTML
          curl -k -v -L "${{ secrets.RAPSITE_APP_URL }}/api/export-dashboard" -o "docs/dashboard/index.html"
          
          # Download client landing page HTML
          curl -k -v -L "${{ secrets.RAPSITE_APP_URL }}/api/export/${{ github.event.client_payload.slug }}" -o "docs/${{ github.event.client_payload.slug }}/index.html"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "deploy: update landing page static folder for '${{ github.event.client_payload.slug }}'" || exit 0
          git push origin main
